-- =====================================================================
-- S-004 (OPCIONAL, NO se ejecuta automáticamente) — Familias y Líneas de producto de CASA MINGO
-- Origen: listas que estaban fijas en el formulario de Productos (retiradas del código en el commit 23fd404 al conectarlo al banco).
-- Requiere confirmación del responsable de que son el catálogo real de la empresa cliente. Sin códigos (se pueden asignar luego).
-- Uso (solo en un banco autorizado, después de NEX-017):
--   psql -v empresa_codigo=casa-mingo -f S-004-casa-mingo-familias-lineas.sql
-- Idempotente (ON CONFLICT DO NOTHING). Aborta si la empresa no existe o es DEMO. No toca productos existentes.
-- =====================================================================
\set ON_ERROR_STOP on
\if :{?empresa_codigo}
\else
  \echo 'FALTA -v empresa_codigo=<código de la empresa>'
  \quit
\endif
SELECT count(*) > 0 AS existe, coalesce(max(id::text), '') AS emp FROM empresas WHERE codigo = :'empresa_codigo' AND NOT es_demo \gset
\if :existe
\else
  \echo 'La empresa no existe o es DEMO: nada se carga.'
  \quit
\endif
BEGIN;
INSERT INTO familias_producto (empresa_id, nombre) VALUES
  (:'emp', 'ACCESORIOS DE VINO'),
  (:'emp', 'BOLS'),
  (:'emp', 'BOTELLA'),
  (:'emp', 'CACEROLA'),
  (:'emp', 'CAFETERA'),
  (:'emp', 'CAFETERIA'),
  (:'emp', 'CASEROLA'),
  (:'emp', 'CENICERO'),
  (:'emp', 'COCTELERA'),
  (:'emp', 'COCTELERIA'),
  (:'emp', 'COKTAIL'),
  (:'emp', 'COMPOTERAS'),
  (:'emp', 'COPAS EN ESTUCHES'),
  (:'emp', 'COPAS SUELTAS'),
  (:'emp', 'DECANTER'),
  (:'emp', 'DESCORCHADOR'),
  (:'emp', 'ENSALADERAS'),
  (:'emp', 'ESTUCHE DE COPAS'),
  (:'emp', 'ESTUCHE DE VASOS'),
  (:'emp', 'FLANERO'),
  (:'emp', 'FUENTE'),
  (:'emp', 'FUENTES'),
  (:'emp', 'HUEVERA'),
  (:'emp', 'JARRA'),
  (:'emp', 'JARRA MEDIDORA'),
  (:'emp', 'JARRO'),
  (:'emp', 'JGO DE JARRA DE VASOS'),
  (:'emp', 'JGO DE PLATOS'),
  (:'emp', 'MANIJAS'),
  (:'emp', 'MANTEQUERITA'),
  (:'emp', 'MIXING'),
  (:'emp', 'MOLDE'),
  (:'emp', 'MOLINILLO'),
  (:'emp', 'PLATO'),
  (:'emp', 'PLATOS'),
  (:'emp', 'RAMEQUIN'),
  (:'emp', 'SALERO'),
  (:'emp', 'SERVILLETAS'),
  (:'emp', 'TARRO C/ DISEÑO'),
  (:'emp', 'TARROS TRANSP'),
  (:'emp', 'TARTERA'),
  (:'emp', 'TAZA'),
  (:'emp', 'TAZA C/ PLATITO'),
  (:'emp', 'TAZA C/PLATO'),
  (:'emp', 'TAZA CAPUCHINO'),
  (:'emp', 'TAZA S/ PLATO'),
  (:'emp', 'TUPPERS'),
  (:'emp', 'UTENSILLOS DE COCINA'),
  (:'emp', 'VASOS EN ESTUCHES'),
  (:'emp', 'VASOS SUELTOS'),
  (:'emp', 'VINAGRERO')
ON CONFLICT DO NOTHING;
INSERT INTO lineas_producto (empresa_id, familia_id, nombre)
SELECT :'emp', f.id, v.linea FROM (VALUES
  ('ACCESORIOS DE VINO', 'DESCAPSULADOR'),
  ('ACCESORIOS DE VINO', 'SACACORCHO'),
  ('ACCESORIOS DE VINO', 'SACACORCHOS'),
  ('ACCESORIOS DE VINO', 'SARTEN'),
  ('BOLS', 'CARINE NOIR'),
  ('BOLS', 'COSMOS'),
  ('BOLS', 'EVOLUTION PEPS'),
  ('BOLS', 'FLASHY'),
  ('BOLS', 'HOTELIERE'),
  ('BOLS', 'OCUISINE'),
  ('BOLS', 'STRUCTURE TRANSPARENTE'),
  ('BOTELLA', 'FLUID'),
  ('CACEROLA', 'INDUCCION'),
  ('CACEROLA', 'OCUISINE'),
  ('CAFETERA', 'A GAS'),
  ('CAFETERA', 'INDUCCION'),
  ('CAFETERA', 'PRENSA'),
  ('CAFETERA', 'RECAMBIO'),
  ('CASEROLA', 'OCUISINE'),
  ('CENICERO', 'CENICEROS'),
  ('COCTELERA', 'COCKTAIL'),
  ('COKTAIL', 'NEW YORK'),
  ('COMPOTERAS', 'CARINE BLANCO'),
  ('COMPOTERAS', 'CARINE NEGRO'),
  ('COMPOTERAS', 'DIWALI BLANCO'),
  ('COMPOTERAS', 'EVOLUTION PEPS'),
  ('COMPOTERAS', 'QUADRATO BLANCO'),
  ('COMPOTERAS', 'QUADRATO NEGRO'),
  ('COMPOTERAS', 'STRUCTURE SHELLS BCO'),
  ('COPAS EN ESTUCHES', 'BALLON'),
  ('COPAS EN ESTUCHES', 'COCTKAIL'),
  ('COPAS EN ESTUCHES', 'ELEGANCE'),
  ('COPAS EN ESTUCHES', 'EUKLASE'),
  ('COPAS EN ESTUCHES', 'EXALTACION'),
  ('COPAS EN ESTUCHES', 'GRAND CHAIS'),
  ('COPAS EN ESTUCHES', 'MALVIDES'),
  ('COPAS EN ESTUCHES', 'OPEN UP'),
  ('COPAS EN ESTUCHES', 'PALMIER'),
  ('COPAS EN ESTUCHES', 'PRINCESA'),
  ('COPAS EN ESTUCHES', 'QUADRO'),
  ('COPAS EN ESTUCHES', 'REVEAL UP'),
  ('COPAS EN ESTUCHES', 'SO WINE'),
  ('COPAS EN ESTUCHES', 'SPIRITS'),
  ('COPAS EN ESTUCHES', 'SYMETRIE'),
  ('COPAS EN ESTUCHES', 'TULIPE'),
  ('COPAS SUELTAS', 'BROADWAY'),
  ('COPAS SUELTAS', 'CERVOISE'),
  ('COPAS SUELTAS', 'COCTKAIL'),
  ('COPAS SUELTAS', 'COÑAC'),
  ('COPAS SUELTAS', 'LICOR'),
  ('COPAS SUELTAS', 'RAINDROP'),
  ('DECANTER', 'ABONDANCE'),
  ('DECANTER', 'MACARON'),
  ('DECANTER', 'OPEN UP'),
  ('ENSALADERAS', 'APILABLE'),
  ('ENSALADERAS', 'CARINE BLANCO'),
  ('ENSALADERAS', 'CARINE NOIR'),
  ('ENSALADERAS', 'COSMOS'),
  ('ENSALADERAS', 'DIWALI BLANCO'),
  ('ENSALADERAS', 'EVOLUTION PEPS'),
  ('ENSALADERAS', 'QUADRATO BLANCO'),
  ('ENSALADERAS', 'QUADRATO NEGRO'),
  ('ESTUCHE DE COPAS', 'LADY DIAMOND'),
  ('ESTUCHE DE COPAS', 'LONGCHAMP'),
  ('ESTUCHE DE COPAS', 'MACASSAR'),
  ('ESTUCHE DE VASOS', 'LADY DIAMOND'),
  ('ESTUCHE DE VASOS', 'LONGCHAMP'),
  ('ESTUCHE DE VASOS', 'MACASSAR'),
  ('FLANERO', 'SMART  CUISINE BCO'),
  ('FUENTE', 'OCUISINE'),
  ('FUENTE', 'SMART  CUISINE BCO'),
  ('FUENTES', 'EVOLUTION PEPS'),
  ('FUENTES', 'QUADRATO NEGRO'),
  ('HUEVERA', 'POULE'),
  ('JARRA', 'ARC'),
  ('JARRA', 'BRIGTON'),
  ('JARRA', 'IMPERATOR'),
  ('JARRA', 'KONE'),
  ('JARRA', 'OCTIME'),
  ('JARRA', 'ORIENT'),
  ('JARRA', 'QUADRO'),
  ('JARRA', 'ROC'),
  ('JARRA', 'TIVOLI'),
  ('JARRA', 'VICTORIA'),
  ('JARRA', 'WHAVY'),
  ('JARRA MEDIDORA', 'OCUISINE'),
  ('JARRO', 'BONE'),
  ('JARRO', 'EVOLUTIONS PEPS'),
  ('JARRO', 'NEW MORNING'),
  ('JARRO', 'NUEVO'),
  ('JARRO', 'TRANSPORTABLE'),
  ('JGO DE JARRA DE VASOS', 'BRIGHTON'),
  ('JGO DE JARRA DE VASOS', 'IMPERATOR'),
  ('JGO DE JARRA DE VASOS', 'MARTIGUES - KONE'),
  ('JGO DE JARRA DE VASOS', 'NEO-KONE'),
  ('JGO DE JARRA DE VASOS', 'OCTIME'),
  ('JGO DE JARRA DE VASOS', 'PALM SPRINGS'),
  ('JGO DE PLATOS', 'CARINE FELITSA'),
  ('MANIJAS', 'CHOOP'),
  ('MANTEQUERITA', 'APILABLE'),
  ('MIXING', 'OCUISINE'),
  ('MOLDE', 'OCUISINE'),
  ('MOLDE', 'SMART  CUISINE BCO'),
  ('MOLINILLO', 'CAFETERIA'),
  ('MOLINILLO', 'PIMENTERO'),
  ('PLATO', 'DIWALI BLANCO'),
  ('PLATOS', 'CARINE BLANCO'),
  ('PLATOS', 'CARINE NEGRO'),
  ('PLATOS', 'CARINE NOIR'),
  ('PLATOS', 'COTTAGE GRANIT'),
  ('PLATOS', 'DIWALI LIGTH TURQUOISE'),
  ('PLATOS', 'EVOLUTION GRANIT'),
  ('PLATOS', 'EVOLUTION PEPS'),
  ('PLATOS', 'EVOLUTION PEPS NEGRO'),
  ('PLATOS', 'HOTELIERE'),
  ('PLATOS', 'INTENSITY BCO'),
  ('PLATOS', 'QUADRATO BLANCO'),
  ('PLATOS', 'QUADRATO NEGRO'),
  ('PLATOS', 'STRUCTURE SHELLS BCO'),
  ('RAMEQUIN', 'SMART  CUISINE BCO'),
  ('SALERO', 'SALERO'),
  ('SERVILLETAS', 'VARIADOS'),
  ('TARRO C/ DISEÑO', 'VARIADOS DISEÑOS'),
  ('TARROS TRANSP', 'PURE JAR CLUB'),
  ('TARTERA', 'OCUISINE'),
  ('TAZA', 'EVOLUTION PEPS'),
  ('TAZA C/ PLATITO', 'CARINE BLANCO'),
  ('TAZA C/ PLATITO', 'EVOLUTION PEPS'),
  ('TAZA C/ PLATITO', 'HOTELIERE'),
  ('TAZA C/PLATO', 'AROMA'),
  ('TAZA CAPUCHINO', 'FOOTED MUG'),
  ('TAZA CAPUCHINO', 'IRISH COFFE'),
  ('TAZA CAPUCHINO', 'LATINO'),
  ('TAZA S/ PLATO', 'AROMA'),
  ('TAZA S/ PLATO', 'FLASHY'),
  ('TAZA S/ PLATO', 'JUMBO'),
  ('TUPPERS', 'EASY BOX AZUL RECTANGULAR'),
  ('TUPPERS', 'EASY BOX CUADRADO'),
  ('TUPPERS', 'EASY BOX REDONDO'),
  ('TUPPERS', 'KEEP LAGON CUADRADO'),
  ('TUPPERS', 'KEEP LAGON RECTANGULAR'),
  ('TUPPERS', 'KEEP LAGON REDONDO'),
  ('TUPPERS', 'PURE BOX  REDONDO'),
  ('TUPPERS', 'PURE BOX CUADRADO'),
  ('TUPPERS', 'PURE BOX RECTANGULAR'),
  ('UTENSILLOS DE COCINA', 'CIERRA BOLSAS'),
  ('UTENSILLOS DE COCINA', 'CORTADOR'),
  ('UTENSILLOS DE COCINA', 'CUCHARA'),
  ('UTENSILLOS DE COCINA', 'CUCHARON'),
  ('UTENSILLOS DE COCINA', 'DISPENSADOR'),
  ('UTENSILLOS DE COCINA', 'ENCENDEDOR'),
  ('UTENSILLOS DE COCINA', 'ESPATULA'),
  ('UTENSILLOS DE COCINA', 'ESPIRALIZADOR'),
  ('UTENSILLOS DE COCINA', 'ESPUMADERA'),
  ('UTENSILLOS DE COCINA', 'ESPÁTULA'),
  ('UTENSILLOS DE COCINA', 'ESTANTE'),
  ('UTENSILLOS DE COCINA', 'EXPRIMIDOR'),
  ('UTENSILLOS DE COCINA', 'GUANTE'),
  ('UTENSILLOS DE COCINA', 'MANDOLINA'),
  ('UTENSILLOS DE COCINA', 'MANGA'),
  ('UTENSILLOS DE COCINA', 'PALETA'),
  ('UTENSILLOS DE COCINA', 'PELADOR'),
  ('UTENSILLOS DE COCINA', 'PINCEL'),
  ('UTENSILLOS DE COCINA', 'PINZA'),
  ('UTENSILLOS DE COCINA', 'RALLADOR'),
  ('UTENSILLOS DE COCINA', 'REBANADOR'),
  ('UTENSILLOS DE COCINA', 'REMOVEDOR'),
  ('UTENSILLOS DE COCINA', 'RODILLO'),
  ('UTENSILLOS DE COCINA', 'ROMPE'),
  ('UTENSILLOS DE COCINA', 'ROMPENUECES'),
  ('UTENSILLOS DE COCINA', 'SOPLETE'),
  ('UTENSILLOS DE COCINA', 'TABLA'),
  ('UTENSILLOS DE COCINA', 'TAMIZADOR'),
  ('UTENSILLOS DE COCINA', 'TRINCHAPOLLOS'),
  ('UTENSILLOS DE COCINA', 'TRITURADOR'),
  ('VASOS EN ESTUCHES', 'ASCOT'),
  ('VASOS EN ESTUCHES', 'IMPERATOR'),
  ('VASOS EN ESTUCHES', 'ISLANDE'),
  ('VASOS EN ESTUCHES', 'OCTIME'),
  ('VASOS EN ESTUCHES', 'OCTIME DIAMOND'),
  ('VASOS EN ESTUCHES', 'OPEN UP'),
  ('VASOS EN ESTUCHES', 'SALTO ICE BLUE'),
  ('VASOS EN ESTUCHES', 'SALTO ICE PINK'),
  ('VASOS EN ESTUCHES', 'STERLING ICE BLUE'),
  ('VASOS EN ESTUCHES', 'STERLING ICE PINK'),
  ('VASOS EN ESTUCHES', 'STERLING TRANSP'),
  ('VASOS SUELTOS', 'ARCADIE'),
  ('VASOS SUELTOS', 'BOURDON'),
  ('VASOS SUELTOS', 'BRASIERE'),
  ('VASOS SUELTOS', 'BROADWAY'),
  ('VASOS SUELTOS', 'GASTON SKALE'),
  ('VASOS SUELTOS', 'GIN'),
  ('VASOS SUELTOS', 'GRANITY'),
  ('VASOS SUELTOS', 'HOT SHOT'),
  ('VASOS SUELTOS', 'ISLANDE'),
  ('VASOS SUELTOS', 'LINZ'),
  ('VASOS SUELTOS', 'MARTIGUES'),
  ('VASOS SUELTOS', 'NEW AMERICA'),
  ('VASOS SUELTOS', 'OLD SQUARE'),
  ('VASOS SUELTOS', 'PRIMARY'),
  ('VASOS SUELTOS', 'SALTO'),
  ('VASOS SUELTOS', 'STARLINE'),
  ('VINAGRERO', 'VINAGRERO')
) AS v(familia, linea)
JOIN familias_producto f ON f.empresa_id = :'emp' AND lower(btrim(f.nombre)) = lower(btrim(v.familia))
ON CONFLICT DO NOTHING;
COMMIT;
SELECT (SELECT count(*) FROM familias_producto WHERE empresa_id = :'emp') AS familias, (SELECT count(*) FROM lineas_producto WHERE empresa_id = :'emp') AS lineas;
