-- Catálogo de países desde Paises_v100.xsd publicado por SIFEN.
-- Fuente: https://ekuatia.set.gov.py/sifen/xsd/Paises_v100.xsd (archivo local: Paises_v100.xsd)
-- SHA-256 del XSD: b75edd6b8ee0a10115104b7f0a5f6963485e41d3b78bcb5ef715a0763ecdc592
-- Países verificados en el XSD: 248
-- Idempotente. Conserva todos los registros existentes: no elimina ni desactiva países y
-- no cambia 'activo'. Solo inserta los faltantes y alinea 'nombre' con el XSD oficial
-- cuando difiere (los nombres ya copiados en clientes/proveedores no se tocan).
-- Ejecutar con: psql -v ON_ERROR_STOP=1 -1 -f CARGA-PAISES-SIFEN.sql
BEGIN;
INSERT INTO referencia_geografica_paises (codigo, nombre) VALUES
  ('ABW', 'Aruba'),
  ('AFG', 'Afganistán'),
  ('AGO', 'Angola'),
  ('AIA', 'Anguila'),
  ('ALA', 'Islas Åland'),
  ('ALB', 'Albania'),
  ('AND', 'Andorra'),
  ('ARE', 'Emiratos Árabes Unidos'),
  ('ARG', 'Argentina'),
  ('ARM', 'Armenia'),
  ('ASM', 'Samoa Americana'),
  ('ATA', 'Antártida'),
  ('ATF', 'Territorio de las Tierras Australes Francesas'),
  ('ATG', 'Antigua y Barbuda'),
  ('AUS', 'Australia'),
  ('AUT', 'Austria'),
  ('AZE', 'Azerbaiyán'),
  ('BDI', 'Burundi'),
  ('BEL', 'Bélgica'),
  ('BEN', 'Benin'),
  ('BES', 'Bonaire, San Eustaquio y Saba'),
  ('BFA', 'Burkina Faso'),
  ('BGD', 'Bangladesh'),
  ('BGR', 'Bulgaria'),
  ('BHR', 'Bahrein'),
  ('BHS', 'Bahamas'),
  ('BIH', 'Bosnia y Herzegovina'),
  ('BLM', 'San Bartolomé'),
  ('BLR', 'Belarús'),
  ('BLZ', 'Belice'),
  ('BMU', 'Bermuda'),
  ('BOL', 'Bolivia (Estado Plurinacional de)'),
  ('BRA', 'Brasil'),
  ('BRB', 'Barbados'),
  ('BRN', 'Brunei Darussalam'),
  ('BTN', 'Bhután'),
  ('BWA', 'Botswana'),
  ('CAF', 'República Centroafricana'),
  ('CAN', 'Canadá'),
  ('CCK', 'Islas Cocos (Keeling)'),
  ('CHE', 'Suiza'),
  ('CHL', 'Chile'),
  ('CHN', 'China'),
  ('CIV', 'Côte d''Ivoire'),
  ('CMR', 'Camerún'),
  ('COD', 'República Democrática del Congo'),
  ('COG', 'Congo'),
  ('COK', 'Islas Cook'),
  ('COL', 'Colombia'),
  ('COM', 'Comoras'),
  ('CPV', 'Cabo Verde'),
  ('CRI', 'Costa Rica'),
  ('CUB', 'CUBA'),
  ('CUW', 'Curaçao'),
  ('CXR', 'Isla de Navidad'),
  ('CYM', 'Islas Caimán'),
  ('CYP', 'Chipre'),
  ('CZE', 'Chequia'),
  ('DEU', 'Alemania'),
  ('DJI', 'Djibouti'),
  ('DMA', 'Dominica'),
  ('DNK', 'Dinamarca'),
  ('DOM', 'República Dominicana'),
  ('DZA', 'Argelia'),
  ('ECU', 'Ecuador'),
  ('EGY', 'Egipto'),
  ('ERI', 'Eritrea'),
  ('ESH', 'Sáhara Occidental'),
  ('ESP', 'España'),
  ('EST', 'Estonia'),
  ('ETH', 'Etiopía'),
  ('FIN', 'Finlandia'),
  ('FJI', 'Fiji'),
  ('FLK', 'Islas Malvinas (Falkland)'),
  ('FRA', 'Francia'),
  ('FRO', 'Islas Feroe'),
  ('FSM', 'Micronesia (Estados Federados de)'),
  ('GAB', 'Gabón'),
  ('GBR', 'Reino Unido de Gran Bretaña e Irlanda del Norte'),
  ('GEO', 'Georgia'),
  ('GGY', 'Guernsey'),
  ('GHA', 'Ghana'),
  ('GIB', 'Gibraltar'),
  ('GIN', 'Guinea'),
  ('GLP', 'Guadalupe'),
  ('GMB', 'Gambia'),
  ('GNB', 'Guinea-Bissau'),
  ('GNQ', 'Guinea Ecuatorial'),
  ('GRC', 'Grecia'),
  ('GRD', 'Granada'),
  ('GRL', 'Groenlandia'),
  ('GTM', 'Guatemala'),
  ('GUF', 'Guayana Francesa'),
  ('GUM', 'Guam'),
  ('GUY', 'Guyana'),
  ('HKG', 'Hong Kong'),
  ('HMD', 'Islas Heard y McDonald'),
  ('HND', 'Honduras'),
  ('HRV', 'Croacia'),
  ('HTI', 'Haití'),
  ('HUN', 'Hungría'),
  ('IDN', 'Indonesia'),
  ('IMN', 'Isla de Man'),
  ('IND', 'India'),
  ('IOT', 'Territorio Británico del Océano Índico'),
  ('IRL', 'Irlanda'),
  ('IRN', 'Irán (República Islámica del)'),
  ('IRQ', 'Iraq'),
  ('ISL', 'Islandia'),
  ('ISR', 'Israel'),
  ('ITA', 'Italia'),
  ('JAM', 'Jamaica'),
  ('JEY', 'Jersey'),
  ('JOR', 'Jordania'),
  ('JPN', 'Japón'),
  ('KAZ', 'Kazajstán'),
  ('KEN', 'Kenya'),
  ('KGZ', 'Kirguistán'),
  ('KHM', 'Camboya'),
  ('KIR', 'Kiribati'),
  ('KNA', 'Saint Kitts y Nevis'),
  ('KOR', 'República de Corea'),
  ('KWT', 'Kuwait'),
  ('LAO', 'República Democrática Popular Lao'),
  ('LBN', 'Líbano'),
  ('LBR', 'Liberia'),
  ('LBY', 'Libia'),
  ('LCA', 'Santa Lucía'),
  ('LIE', 'Liechtenstein'),
  ('LKA', 'Sri Lanka'),
  ('LSO', 'Lesotho'),
  ('LTU', 'Lituania'),
  ('LUX', 'Luxemburgo'),
  ('LVA', 'Letonia'),
  ('MAC', 'Macao'),
  ('MAF', 'San Martín (parte francesa)'),
  ('MAR', 'Marruecos'),
  ('MCO', 'Mónaco'),
  ('MDA', 'República de Moldova'),
  ('MDG', 'Madagascar'),
  ('MDV', 'Maldivas'),
  ('MEX', 'México'),
  ('MHL', 'Islas Marshall'),
  ('MKD', 'Macedonia del Norte'),
  ('MLI', 'Malí'),
  ('MLT', 'Malta'),
  ('MMR', 'Myanmar'),
  ('MNE', 'Montenegro'),
  ('MNG', 'Mongolia'),
  ('MNP', 'Islas Marianas Septentrionales'),
  ('MOZ', 'Mozambique'),
  ('MRT', 'Mauritania'),
  ('MSR', 'Montserrat'),
  ('MTQ', 'Martinica'),
  ('MUS', 'Mauricio'),
  ('MWI', 'Malawi'),
  ('MYS', 'Malasia'),
  ('MYT', 'Mayotte'),
  ('NAM', 'Namibia'),
  ('NCL', 'Nueva Caledonia'),
  ('NER', 'Níger'),
  ('NFK', 'Islas Norfolk'),
  ('NGA', 'Nigeria'),
  ('NIC', 'Nicaragua'),
  ('NIU', 'Niue'),
  ('NLD', 'Países Bajos'),
  ('NOR', 'Noruega'),
  ('NPL', 'Nepal'),
  ('NRU', 'Nauru'),
  ('NZL', 'Nueva Zelandia'),
  ('OMN', 'Omán'),
  ('PAK', 'Pakistán'),
  ('PAN', 'Panamá'),
  ('PCN', 'Pitcairn'),
  ('PER', 'Perú'),
  ('PHL', 'Filipinas'),
  ('PLW', 'Palau'),
  ('PNG', 'Papua Nueva Guinea'),
  ('POL', 'Polonia'),
  ('PRI', 'Puerto Rico'),
  ('PRK', 'República Popular Democrática de Corea'),
  ('PRT', 'Portugal'),
  ('PRY', 'Paraguay'),
  ('PSE', 'Estado de Palestina'),
  ('PYF', 'Polinesia Francesa'),
  ('QAT', 'Qatar'),
  ('REU', 'Reunión'),
  ('ROU', 'Rumania'),
  ('RUS', 'Federación de Rusia'),
  ('RWA', 'Rwanda'),
  ('SAU', 'Arabia Saudita'),
  ('SDN', 'Sudán'),
  ('SEN', 'Senegal'),
  ('SGP', 'Singapur'),
  ('SGS', 'Georgia del Sur y las Islas Sandwich del Sur'),
  ('SHN', 'Santa Elena'),
  ('SJM', 'Islas Svalbard y Jan Mayen'),
  ('SLB', 'Islas Salomón'),
  ('SLE', 'Sierra Leona'),
  ('SLV', 'El Salvador'),
  ('SMR', 'San Marino'),
  ('SOM', 'Somalia'),
  ('SPM', 'Saint Pierre y Miquelon'),
  ('SRB', 'Serbia'),
  ('SSD', 'Sudán del Sur'),
  ('STP', 'Santo Tomé y Príncipe'),
  ('SUR', 'Suriname'),
  ('SVK', 'Eslovaquia'),
  ('SVN', 'Eslovenia'),
  ('SWE', 'Suecia'),
  ('SWZ', 'Swazilandia'),
  ('SXM', 'San Martín (parte holandés)'),
  ('SYC', 'Seychelles'),
  ('SYR', 'República Árabe Siria'),
  ('TCA', 'Islas Turcas y Caicos'),
  ('TCD', 'Chad'),
  ('TGO', 'Togo'),
  ('THA', 'Tailandia'),
  ('TJK', 'Tayikistán'),
  ('TKL', 'Tokelau'),
  ('TKM', 'Turkmenistán'),
  ('TLS', 'Timor-Leste'),
  ('TON', 'Tonga'),
  ('TTO', 'Trinidad y Tabago'),
  ('TUN', 'Túnez'),
  ('TUR', 'Turquía'),
  ('TUV', 'Tuvalu'),
  ('TWN', 'Taiwán (Provincia de China)'),
  ('TZA', 'República Unida de Tanzanía'),
  ('UGA', 'Uganda'),
  ('UKR', 'Ucrania'),
  ('UMI', 'Islas menores alejadas de Estados Unidos'),
  ('URY', 'Uruguay'),
  ('USA', 'Estados Unidos de América'),
  ('UZB', 'Uzbekistán'),
  ('VAT', 'Santa Sede'),
  ('VCT', 'San Vicente y las Granadinas'),
  ('VEN', 'Venezuela (República Bolivariana de)'),
  ('VGB', 'Islas Vírgenes Británicas'),
  ('VIR', 'Islas Vírgenes de los Estados Unidos'),
  ('VNM', 'Viet Nam'),
  ('VUT', 'Vanuatu'),
  ('WLF', 'Islas Wallis y Futuna'),
  ('WSM', 'Samoa'),
  ('YEM', 'Yemen'),
  ('ZAF', 'Sudáfrica'),
  ('ZMB', 'Zambia'),
  ('ZWE', 'Zimbabwe')
ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre, actualizado_at = now()
  WHERE referencia_geografica_paises.nombre IS DISTINCT FROM EXCLUDED.nombre;
COMMIT;
